### ISSUE TITLE
sluggish performance

### ISSUE THREAD

**Issue by davephillips** [loudnumbers/loudnumbers_vcv#13]
I've used your module in earlier versions without performance issues, but the most recent build is noticeably slower than my previous builds. The particular CSV file doesn't seem to matter. Debugging symbols maybe ? I'm using it with a local build of VCV Rack 2 on a Mac Mini M1. Please let me know if there's anything I can do for tests, I like this module. :)

**Comment by duncangeere** [comment]
Hey Dave! Is that the new version I just pushed to this repo or the version
currently in the VCV library?

**Comment by davephillips** [comment]
I compiled the latest git code.

`commit 34834ef019ab7ef047bdf1d6c5aa83a9847d47e8`

**Comment by duncangeere** [comment]
Ah yes, that’s a little “in progress”. Working on a fix :) I’ll reach out if I need more info!

**Comment by duncangeere** [comment]
@davephillips Can I ask - how big was the dataset you were using when you encountered slow behaviour? (i.e. how many rows)

I'm finding performance suffers on my M1 Macbook Pro when I get above a few hundred rows, and trying to figure out why... the only time I've seen this in the past is when I've been excessively logging, but all the log statements are removed in the latest code...

Could you talk a bit more about what you mean by debugging symbols? I'm not so familiar with the term, and Googling isn't helping much!

**Comment by duncangeere** [comment]
Ah! I think I may have found the answer. It was a bug with drawing the visuals. Can you try the latest commit (https://github.com/loudnumbers/loudnumbers_vcv/commit/29230489386b5646dc73479680cd28493e279379) and see if that's better?

**Comment by davephillips** [comment]
Yep, much better now, thanks for the fix. I tested various CSV files, no problems loading anything yet. :)

**Comment by duncangeere** [comment]
Woohoo! I think the problem was that I was accidentally drawing thousands of invisible SVG circles 🫠

gonna call this solved, but feel free to reopen if it rears its ugly head again.
